apiVersion: v1
kind: Secret
metadata:
  name: myminio-env-configuration
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER=minioadmin
    export MINIO_ROOT_PASSWORD=minioadminpassword
