apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-gp2
  namespace: minio
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: xfs
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
